name: RL_Assign2
channels:
  - defaults
  - anaconda
dependencies:
  - python>=3.9,<3.10
  - pip
  - tensorflow-gpu
  - numpy
  - tqdm
  - pip:
      - gymnasium[classic-control]  # need this for rendering
      - ruff  # dev