name: RL_Assign1
channels:
  - defaults
dependencies:
  - python==3.10
  - pip
  - gymnasium
  - tensorflow
  - tensorflow-gpu  # for gpu training
  - numpy
  - matplotlib
  - tqdm
  - pip:
      - ruff  # dev