name: RL_Assign3
channels:
  - defaults
  - anaconda
dependencies:
  - python>=3.9,<3.10
  - pip
  - tensorflow-gpu
  - keras
  - numpy>=1.21,<1.24
  - scikit-learn
  - tqdm
  - pip:
      - gymnasium[classic-control]  # need this for rendering
      - ruff  # dev